# -*- coding: utf-8 -*-
"""01_Time_Converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpMP08KRpE6NSJ8t5qV2wsDl2pfy0LQI
"""



# Convert minutes into readable format

minutes = int(input("Enter minutes: "))

hours = minutes // 60
remaining = minutes % 60

if hours > 0:
    if hours == 1:
        print(f"{hours} hr {remaining} minutes")
    else:
        print(f"{hours} hrs {remaining} minutes")
else:
    print(f"{remaining} minutes")