# -*- coding: utf-8 -*-
"""02_Remove_Duplicates

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bhToKRiPg9rj9CD0ZopN_Z-rsn1WKKa_
"""

# Remove duplicate characters from string

s = input("Enter string: ")
result = ""

for char in s:
    if char not in result:
        result += char

print("Unique string:", result)